# Generated by Django 2.2.6 on 2020-07-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0002_auto_20200709_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_take',
            field=models.BooleanField(default=False),
        ),
    ]
